# Generated by Django 2.1.7 on 2020-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200408_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='daily_use',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='projected_daily_use',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='projected_run_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
