branch-defaults:
  master:
    environment: ppetrackr-dev
environment-defaults:
  ppetrackr-prod:
    branch: null
    repository: null
global:
  application_name: ppetrackr
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
